export interface Food {
  id: string;
  name: string;
  brand?: string;
  servingSize: number;
  servingUnit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  verified: boolean;
  lastUsedAt: string | null;
}

export const mockFoods: Food[] = [
  {
    id: 'food-chicken-breast',
    name: 'Chicken Breast',
    servingSize: 4,
    servingUnit: 'oz',
    calories: 187,
    protein: 35,
    carbs: 0,
    fat: 4,
    verified: true,
    lastUsedAt: '2026-03-05T12:30:00.000Z',
  },
  {
    id: 'food-rice',
    name: 'White Rice',
    servingSize: 1,
    servingUnit: 'cup',
    calories: 205,
    protein: 4,
    carbs: 45,
    fat: 0,
    fiber: 1,
    verified: true,
    lastUsedAt: '2026-03-05T12:30:00.000Z',
  },
  {
    id: 'food-eggs',
    name: 'Large Eggs',
    servingSize: 2,
    servingUnit: 'eggs',
    calories: 140,
    protein: 12,
    carbs: 1,
    fat: 10,
    verified: true,
    lastUsedAt: '2026-03-05T07:15:00.000Z',
  },
  {
    id: 'food-oats',
    name: 'Rolled Oats',
    brand: "Bob's Red Mill",
    servingSize: 0.5,
    servingUnit: 'cup',
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    fiber: 4,
    verified: true,
    lastUsedAt: '2026-03-04T07:10:00.000Z',
  },
  {
    id: 'food-banana',
    name: 'Banana',
    servingSize: 1,
    servingUnit: 'medium',
    calories: 105,
    protein: 1,
    carbs: 27,
    fat: 0,
    fiber: 3,
    verified: true,
    lastUsedAt: '2026-03-05T07:15:00.000Z',
  },
  {
    id: 'food-sweet-potato',
    name: 'Sweet Potato',
    servingSize: 1,
    servingUnit: 'medium',
    calories: 112,
    protein: 2,
    carbs: 26,
    fat: 0,
    fiber: 4,
    verified: true,
    lastUsedAt: '2026-03-04T18:45:00.000Z',
  },
  {
    id: 'food-salmon',
    name: 'Atlantic Salmon',
    servingSize: 5,
    servingUnit: 'oz',
    calories: 290,
    protein: 31,
    carbs: 0,
    fat: 17,
    verified: true,
    lastUsedAt: '2026-03-05T18:40:00.000Z',
  },
  {
    id: 'food-greek-yogurt',
    name: 'Greek Yogurt',
    brand: 'Fage 0%',
    servingSize: 170,
    servingUnit: 'g',
    calories: 90,
    protein: 18,
    carbs: 5,
    fat: 0,
    verified: true,
    lastUsedAt: '2026-03-05T15:30:00.000Z',
  },
  {
    id: 'food-almonds',
    name: 'Almonds',
    servingSize: 1,
    servingUnit: 'oz',
    calories: 164,
    protein: 6,
    carbs: 6,
    fat: 14,
    fiber: 4,
    verified: true,
    lastUsedAt: '2026-03-03T20:20:00.000Z',
  },
  {
    id: 'food-protein-powder',
    name: 'Whey Protein',
    brand: 'Optimum Nutrition Gold Standard',
    servingSize: 1,
    servingUnit: 'scoop',
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1,
    verified: true,
    lastUsedAt: '2026-03-05T16:45:00.000Z',
  },
  {
    id: 'food-broccoli',
    name: 'Broccoli',
    servingSize: 1,
    servingUnit: 'cup',
    calories: 31,
    protein: 3,
    carbs: 6,
    fat: 0,
    fiber: 2,
    verified: true,
    lastUsedAt: '2026-03-05T12:30:00.000Z',
  },
  {
    id: 'food-olive-oil',
    name: 'Olive Oil',
    brand: 'California Olive Ranch',
    servingSize: 1,
    servingUnit: 'tbsp',
    calories: 119,
    protein: 0,
    carbs: 0,
    fat: 14,
    verified: true,
    lastUsedAt: '2026-03-04T18:45:00.000Z',
  },
  {
    id: 'food-bread',
    name: 'Whole Wheat Bread',
    brand: "Dave's Killer Bread",
    servingSize: 2,
    servingUnit: 'slices',
    calories: 220,
    protein: 10,
    carbs: 44,
    fat: 2,
    fiber: 6,
    verified: true,
    lastUsedAt: '2026-03-05T07:15:00.000Z',
  },
  {
    id: 'food-avocado',
    name: 'Avocado',
    servingSize: 0.5,
    servingUnit: 'fruit',
    calories: 120,
    protein: 2,
    carbs: 6,
    fat: 11,
    fiber: 5,
    verified: true,
    lastUsedAt: '2026-03-02T12:15:00.000Z',
  },
  {
    id: 'food-ground-beef',
    name: 'Ground Beef 90/10',
    servingSize: 4,
    servingUnit: 'oz',
    calories: 200,
    protein: 23,
    carbs: 0,
    fat: 11,
    verified: true,
    lastUsedAt: '2026-03-03T18:30:00.000Z',
  },
  {
    id: 'food-milk',
    name: '2% Milk',
    brand: 'Fairlife',
    servingSize: 1,
    servingUnit: 'cup',
    calories: 120,
    protein: 13,
    carbs: 6,
    fat: 4,
    verified: true,
    lastUsedAt: '2026-03-04T07:10:00.000Z',
  },
  {
    id: 'food-peanut-butter',
    name: 'Peanut Butter',
    brand: 'Jif Natural',
    servingSize: 2,
    servingUnit: 'tbsp',
    calories: 190,
    protein: 7,
    carbs: 7,
    fat: 16,
    fiber: 2,
    verified: false,
    lastUsedAt: '2026-03-03T15:45:00.000Z',
  },
  {
    id: 'food-apple',
    name: 'Apple',
    servingSize: 1,
    servingUnit: 'medium',
    calories: 95,
    protein: 0,
    carbs: 25,
    fat: 0,
    fiber: 4,
    verified: true,
    lastUsedAt: '2026-03-04T15:20:00.000Z',
  },
  {
    id: 'food-spinach',
    name: 'Spinach',
    servingSize: 2,
    servingUnit: 'cups',
    calories: 14,
    protein: 2,
    carbs: 2,
    fat: 0,
    fiber: 1,
    verified: true,
    lastUsedAt: '2026-03-05T18:40:00.000Z',
  },
  {
    id: 'food-cheese',
    name: 'Cheddar Cheese',
    brand: 'Tillamook',
    servingSize: 1,
    servingUnit: 'oz',
    calories: 110,
    protein: 7,
    carbs: 1,
    fat: 9,
    verified: true,
    lastUsedAt: null,
  },
];
