export interface FoodItem {
  id: string;
  foodId: string;
  name: string;
  servingSize: number;
  servingUnit: string;
  quantity: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

export interface Meal {
  id: string;
  name: 'Breakfast' | 'Lunch' | 'Dinner' | 'Snacks';
  time: string;
  items: FoodItem[];
}

export interface DailyMeals {
  [date: string]: Meal[];
}

export interface DailyTargets {
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

export const mockDailyTargets: DailyTargets = {
  calories: 2200,
  protein: 180,
  carbs: 250,
  fat: 73,
};

export const mockDailyMeals: DailyMeals = {
  '2026-03-03': [
    {
      id: 'meal-2026-03-03-breakfast',
      name: 'Breakfast',
      time: '7:15 AM',
      items: [
        {
          id: 'item-2026-03-03-eggs',
          foodId: 'food-eggs',
          name: 'Large Eggs',
          servingSize: 2,
          servingUnit: 'eggs',
          quantity: 1,
          calories: 140,
          protein: 12,
          carbs: 1,
          fat: 10,
        },
        {
          id: 'item-2026-03-03-bread',
          foodId: 'food-bread',
          name: 'Whole Wheat Bread',
          servingSize: 2,
          servingUnit: 'slices',
          quantity: 1,
          calories: 220,
          protein: 10,
          carbs: 44,
          fat: 2,
        },
        {
          id: 'item-2026-03-03-banana',
          foodId: 'food-banana',
          name: 'Banana',
          servingSize: 1,
          servingUnit: 'medium',
          quantity: 1,
          calories: 105,
          protein: 1,
          carbs: 27,
          fat: 0,
        },
      ],
    },
    {
      id: 'meal-2026-03-03-lunch',
      name: 'Lunch',
      time: '12:25 PM',
      items: [
        {
          id: 'item-2026-03-03-chicken',
          foodId: 'food-chicken-breast',
          name: 'Chicken Breast',
          servingSize: 4,
          servingUnit: 'oz',
          quantity: 1.5,
          calories: 281,
          protein: 52,
          carbs: 0,
          fat: 6,
        },
        {
          id: 'item-2026-03-03-rice',
          foodId: 'food-rice',
          name: 'White Rice',
          servingSize: 1,
          servingUnit: 'cup',
          quantity: 1,
          calories: 205,
          protein: 4,
          carbs: 45,
          fat: 0,
        },
        {
          id: 'item-2026-03-03-broccoli',
          foodId: 'food-broccoli',
          name: 'Broccoli',
          servingSize: 1,
          servingUnit: 'cup',
          quantity: 1,
          calories: 31,
          protein: 3,
          carbs: 6,
          fat: 0,
        },
      ],
    },
    {
      id: 'meal-2026-03-03-dinner',
      name: 'Dinner',
      time: '6:40 PM',
      items: [
        {
          id: 'item-2026-03-03-salmon',
          foodId: 'food-salmon',
          name: 'Atlantic Salmon',
          servingSize: 5,
          servingUnit: 'oz',
          quantity: 1,
          calories: 290,
          protein: 31,
          carbs: 0,
          fat: 17,
        },
        {
          id: 'item-2026-03-03-sweet-potato',
          foodId: 'food-sweet-potato',
          name: 'Sweet Potato',
          servingSize: 1,
          servingUnit: 'medium',
          quantity: 1,
          calories: 112,
          protein: 2,
          carbs: 26,
          fat: 0,
        },
        {
          id: 'item-2026-03-03-spinach',
          foodId: 'food-spinach',
          name: 'Spinach Salad',
          servingSize: 2,
          servingUnit: 'cups',
          quantity: 1,
          calories: 14,
          protein: 2,
          carbs: 2,
          fat: 0,
        },
        {
          id: 'item-2026-03-03-olive-oil',
          foodId: 'food-olive-oil',
          name: 'Olive Oil',
          servingSize: 1,
          servingUnit: 'tbsp',
          quantity: 1,
          calories: 119,
          protein: 0,
          carbs: 0,
          fat: 14,
        },
      ],
    },
    {
      id: 'meal-2026-03-03-snacks',
      name: 'Snacks',
      time: '3:45 PM',
      items: [
        {
          id: 'item-2026-03-03-greek-yogurt',
          foodId: 'food-greek-yogurt',
          name: 'Greek Yogurt',
          servingSize: 170,
          servingUnit: 'g',
          quantity: 1,
          calories: 90,
          protein: 18,
          carbs: 5,
          fat: 0,
        },
        {
          id: 'item-2026-03-03-almonds',
          foodId: 'food-almonds',
          name: 'Almonds',
          servingSize: 1,
          servingUnit: 'oz',
          quantity: 1,
          calories: 164,
          protein: 6,
          carbs: 6,
          fat: 14,
        },
        {
          id: 'item-2026-03-03-protein-shake',
          foodId: 'food-protein-powder',
          name: 'Whey Protein',
          servingSize: 1,
          servingUnit: 'scoop',
          quantity: 1,
          calories: 120,
          protein: 24,
          carbs: 3,
          fat: 1,
        },
      ],
    },
  ],
  '2026-03-04': [
    {
      id: 'meal-2026-03-04-breakfast',
      name: 'Breakfast',
      time: '7:10 AM',
      items: [
        {
          id: 'item-2026-03-04-eggs',
          foodId: 'food-eggs',
          name: 'Large Eggs',
          servingSize: 2,
          servingUnit: 'eggs',
          quantity: 1,
          calories: 140,
          protein: 12,
          carbs: 1,
          fat: 10,
        },
        {
          id: 'item-2026-03-04-oats',
          foodId: 'food-oats',
          name: 'Rolled Oats',
          servingSize: 0.5,
          servingUnit: 'cup',
          quantity: 1,
          calories: 150,
          protein: 5,
          carbs: 27,
          fat: 3,
        },
        {
          id: 'item-2026-03-04-banana',
          foodId: 'food-banana',
          name: 'Banana',
          servingSize: 1,
          servingUnit: 'medium',
          quantity: 1,
          calories: 105,
          protein: 1,
          carbs: 27,
          fat: 0,
        },
      ],
    },
    {
      id: 'meal-2026-03-04-lunch',
      name: 'Lunch',
      time: '12:15 PM',
      items: [
        {
          id: 'item-2026-03-04-chicken',
          foodId: 'food-chicken-breast',
          name: 'Chicken Breast',
          servingSize: 4,
          servingUnit: 'oz',
          quantity: 1.25,
          calories: 234,
          protein: 44,
          carbs: 0,
          fat: 5,
        },
        {
          id: 'item-2026-03-04-rice',
          foodId: 'food-rice',
          name: 'White Rice',
          servingSize: 1,
          servingUnit: 'cup',
          quantity: 1,
          calories: 205,
          protein: 4,
          carbs: 45,
          fat: 0,
        },
        {
          id: 'item-2026-03-04-broccoli',
          foodId: 'food-broccoli',
          name: 'Broccoli',
          servingSize: 1,
          servingUnit: 'cup',
          quantity: 1,
          calories: 31,
          protein: 3,
          carbs: 6,
          fat: 0,
        },
      ],
    },
    {
      id: 'meal-2026-03-04-dinner',
      name: 'Dinner',
      time: '6:45 PM',
      items: [
        {
          id: 'item-2026-03-04-salmon',
          foodId: 'food-salmon',
          name: 'Atlantic Salmon',
          servingSize: 5,
          servingUnit: 'oz',
          quantity: 1,
          calories: 290,
          protein: 31,
          carbs: 0,
          fat: 17,
        },
        {
          id: 'item-2026-03-04-sweet-potato',
          foodId: 'food-sweet-potato',
          name: 'Sweet Potato',
          servingSize: 1,
          servingUnit: 'medium',
          quantity: 1.5,
          calories: 168,
          protein: 3,
          carbs: 39,
          fat: 0,
        },
        {
          id: 'item-2026-03-04-spinach',
          foodId: 'food-spinach',
          name: 'Spinach Salad',
          servingSize: 2,
          servingUnit: 'cups',
          quantity: 1,
          calories: 14,
          protein: 2,
          carbs: 2,
          fat: 0,
        },
      ],
    },
    {
      id: 'meal-2026-03-04-snacks',
      name: 'Snacks',
      time: '8:30 PM',
      items: [
        {
          id: 'item-2026-03-04-greek-yogurt',
          foodId: 'food-greek-yogurt',
          name: 'Greek Yogurt',
          servingSize: 170,
          servingUnit: 'g',
          quantity: 1,
          calories: 90,
          protein: 18,
          carbs: 5,
          fat: 0,
        },
        {
          id: 'item-2026-03-04-almonds',
          foodId: 'food-almonds',
          name: 'Almonds',
          servingSize: 1,
          servingUnit: 'oz',
          quantity: 0.5,
          calories: 82,
          protein: 3,
          carbs: 3,
          fat: 7,
        },
        {
          id: 'item-2026-03-04-protein-shake',
          foodId: 'food-protein-powder',
          name: 'Whey Protein',
          servingSize: 1,
          servingUnit: 'scoop',
          quantity: 1,
          calories: 120,
          protein: 24,
          carbs: 3,
          fat: 1,
        },
      ],
    },
  ],
  '2026-03-05': [
    {
      id: 'meal-2026-03-05-breakfast',
      name: 'Breakfast',
      time: '7:20 AM',
      items: [
        {
          id: 'item-2026-03-05-eggs',
          foodId: 'food-eggs',
          name: 'Large Eggs',
          servingSize: 2,
          servingUnit: 'eggs',
          quantity: 1.5,
          calories: 210,
          protein: 18,
          carbs: 2,
          fat: 15,
        },
        {
          id: 'item-2026-03-05-bread',
          foodId: 'food-bread',
          name: 'Whole Wheat Bread',
          servingSize: 2,
          servingUnit: 'slices',
          quantity: 1,
          calories: 220,
          protein: 10,
          carbs: 44,
          fat: 2,
        },
        {
          id: 'item-2026-03-05-banana',
          foodId: 'food-banana',
          name: 'Banana',
          servingSize: 1,
          servingUnit: 'medium',
          quantity: 1,
          calories: 105,
          protein: 1,
          carbs: 27,
          fat: 0,
        },
      ],
    },
    {
      id: 'meal-2026-03-05-lunch',
      name: 'Lunch',
      time: '12:30 PM',
      items: [
        {
          id: 'item-2026-03-05-chicken',
          foodId: 'food-chicken-breast',
          name: 'Chicken Breast',
          servingSize: 4,
          servingUnit: 'oz',
          quantity: 1.5,
          calories: 281,
          protein: 52,
          carbs: 0,
          fat: 6,
        },
        {
          id: 'item-2026-03-05-rice',
          foodId: 'food-rice',
          name: 'White Rice',
          servingSize: 1,
          servingUnit: 'cup',
          quantity: 1.25,
          calories: 256,
          protein: 5,
          carbs: 56,
          fat: 0,
        },
        {
          id: 'item-2026-03-05-broccoli',
          foodId: 'food-broccoli',
          name: 'Broccoli',
          servingSize: 1,
          servingUnit: 'cup',
          quantity: 1,
          calories: 31,
          protein: 3,
          carbs: 6,
          fat: 0,
        },
      ],
    },
    {
      id: 'meal-2026-03-05-dinner',
      name: 'Dinner',
      time: '6:40 PM',
      items: [
        {
          id: 'item-2026-03-05-salmon',
          foodId: 'food-salmon',
          name: 'Atlantic Salmon',
          servingSize: 5,
          servingUnit: 'oz',
          quantity: 1.2,
          calories: 348,
          protein: 37,
          carbs: 0,
          fat: 20,
        },
        {
          id: 'item-2026-03-05-sweet-potato',
          foodId: 'food-sweet-potato',
          name: 'Sweet Potato',
          servingSize: 1,
          servingUnit: 'medium',
          quantity: 1,
          calories: 112,
          protein: 2,
          carbs: 26,
          fat: 0,
        },
        {
          id: 'item-2026-03-05-spinach',
          foodId: 'food-spinach',
          name: 'Spinach Salad',
          servingSize: 2,
          servingUnit: 'cups',
          quantity: 1,
          calories: 14,
          protein: 2,
          carbs: 2,
          fat: 0,
        },
        {
          id: 'item-2026-03-05-avocado',
          foodId: 'food-avocado',
          name: 'Avocado',
          servingSize: 0.5,
          servingUnit: 'fruit',
          quantity: 1,
          calories: 120,
          protein: 2,
          carbs: 6,
          fat: 11,
        },
      ],
    },
    {
      id: 'meal-2026-03-05-snacks',
      name: 'Snacks',
      time: '4:45 PM',
      items: [
        {
          id: 'item-2026-03-05-greek-yogurt',
          foodId: 'food-greek-yogurt',
          name: 'Greek Yogurt',
          servingSize: 170,
          servingUnit: 'g',
          quantity: 1,
          calories: 90,
          protein: 18,
          carbs: 5,
          fat: 0,
        },
        {
          id: 'item-2026-03-05-almonds',
          foodId: 'food-almonds',
          name: 'Almonds',
          servingSize: 1,
          servingUnit: 'oz',
          quantity: 1,
          calories: 164,
          protein: 6,
          carbs: 6,
          fat: 14,
        },
        {
          id: 'item-2026-03-05-protein-shake',
          foodId: 'food-protein-powder',
          name: 'Whey Protein',
          servingSize: 1,
          servingUnit: 'scoop',
          quantity: 1.5,
          calories: 180,
          protein: 36,
          carbs: 5,
          fat: 2,
        },
      ],
    },
  ],
};
