CREATE TABLE body_check_in_preferences (
 user_id TEXT PRIMARY KEY NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 measurement_cadence_days INTEGER NOT NULL DEFAULT 14,
 length_unit TEXT NOT NULL,
 enabled_sites TEXT NOT NULL,
 anchor_date TEXT NOT NULL,
 reminder_local_time TEXT,
 protocol_version TEXT NOT NULL,
 snoozed_until TEXT,
 last_dismissed_due_date TEXT,
 created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
 updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
 CHECK(measurement_cadence_days BETWEEN 7 AND 90),
 CHECK(length_unit IN ('cm', 'in')),
 CHECK(anchor_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND date(anchor_date, '+0 days') = anchor_date),
 CHECK(reminder_local_time IS NULL OR reminder_local_time GLOB '[0-2][0-9]:[0-5][0-9]')
);
--> statement-breakpoint
CREATE TABLE body_check_ins (
 id TEXT PRIMARY KEY NOT NULL,
 user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 local_date TEXT NOT NULL,
 local_time TEXT,
 status TEXT NOT NULL,
 meal_context TEXT NOT NULL DEFAULT 'unspecified',
 workout_context TEXT NOT NULL DEFAULT 'unspecified',
 pump_present INTEGER,
 unusual_bloating INTEGER,
 notes TEXT,
 protocol_version TEXT NOT NULL,
 source TEXT NOT NULL,
 source_id TEXT,
 count_as_scheduled_occurrence INTEGER NOT NULL DEFAULT 1,
 idempotency_key TEXT,
 idempotency_hash TEXT,
 completed_at INTEGER,
 corrected_at INTEGER,
 corrected_by_source TEXT,
 corrected_by_source_id TEXT,
 correction_reason TEXT,
 created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
 updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
 UNIQUE(user_id, local_date),
 UNIQUE(user_id, idempotency_key),
 CHECK(local_date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' AND date(local_date, '+0 days') = local_date),
 CHECK(local_time IS NULL OR local_time GLOB '[0-2][0-9]:[0-5][0-9]'),
 CHECK(status IN ('draft', 'completed')),
 CHECK(meal_context IN ('unspecified', 'pre_meal', 'post_meal')),
 CHECK(workout_context IN ('unspecified', 'pre_workout', 'post_workout')),
 CHECK(source IN ('user', 'agent_token')),
 CHECK(corrected_by_source IS NULL OR corrected_by_source IN ('user', 'agent_token')),
 CHECK(count_as_scheduled_occurrence IN (0, 1)),
 CHECK((status = 'completed' AND completed_at IS NOT NULL) OR (status = 'draft' AND completed_at IS NULL))
);
--> statement-breakpoint
CREATE INDEX body_check_ins_user_date_idx ON body_check_ins(user_id, local_date);
--> statement-breakpoint
CREATE TABLE body_check_in_measurements (
 id TEXT PRIMARY KEY NOT NULL,
 check_in_id TEXT NOT NULL REFERENCES body_check_ins(id) ON DELETE CASCADE,
 site TEXT NOT NULL,
 laterality TEXT NOT NULL,
 unit_at_entry TEXT NOT NULL,
 reading_1_mm INTEGER NOT NULL,
 reading_2_mm INTEGER,
 reading_3_mm INTEGER,
 canonical_mm INTEGER NOT NULL,
 quality TEXT NOT NULL,
 selected_reading_pair TEXT,
 protocol_id TEXT NOT NULL,
 protocol_version TEXT NOT NULL,
 protocol_name TEXT NOT NULL,
 protocol_instructions TEXT NOT NULL,
 protocol_source_urls TEXT NOT NULL,
 created_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
 updated_at INTEGER NOT NULL DEFAULT (unixepoch() * 1000),
 UNIQUE(check_in_id, site, laterality),
 CHECK(unit_at_entry IN ('cm', 'in')),
 CHECK(reading_1_mm BETWEEN 200 AND 3000 AND (reading_2_mm IS NULL OR reading_2_mm BETWEEN 200 AND 3000) AND (reading_3_mm IS NULL OR reading_3_mm BETWEEN 200 AND 3000) AND canonical_mm BETWEEN 200 AND 3000),
 CHECK(reading_3_mm IS NULL OR reading_2_mm IS NOT NULL),
 CHECK(quality IN ('single_reading','replicated','needs_third_reading','replicated_with_tiebreaker','high_variance')),
 CHECK((site IN ('waist_iliac_crest_nhanes','chest_nipple_line_relaxed','hips_maximum') AND laterality = 'none') OR (site IN ('upper_arm_midpoint_flexed','thigh_midpoint') AND laterality IN ('left','right')))
);
--> statement-breakpoint
CREATE INDEX body_check_in_measurements_check_in_idx ON body_check_in_measurements(check_in_id);
