import {
  BODY_CHECK_IN_CONTRACT_VERSION,
  BODY_PROTOCOL_VERSION,
  bodyCheckInPreferenceSchema,
  bodyCheckInSchema,
  bodyProgressAnalyticsSchema,
  bodyDueStateSchema,
  bodyMeasurementProtocols,
  defaultBodyEnabledSites,
  type BodyDueState,
} from '@pulse/shared';

const now = Date.parse('2026-09-15T12:00:00Z');
const waistProtocol = bodyMeasurementProtocols.waist_iliac_crest_nhanes;
const chestProtocol = bodyMeasurementProtocols.chest_nipple_line_relaxed;

export const populatedBodyPreferenceFixture = bodyCheckInPreferenceSchema.parse({
  contractVersion: BODY_CHECK_IN_CONTRACT_VERSION,
  measurementCadenceDays: 14,
  lengthUnit: 'cm',
  enabledSites: defaultBodyEnabledSites,
  anchorDate: '2026-09-01',
  reminderLocalTime: '08:30',
  protocolVersion: BODY_PROTOCOL_VERSION,
  snoozedUntil: null,
  lastDismissedDueDate: null,
  createdAt: now - 1_000,
  updatedAt: now,
});

export const bodyDueFixture = (state: BodyDueState['state']) =>
  bodyDueStateSchema.parse({
    contractVersion: BODY_CHECK_IN_CONTRACT_VERSION,
    state,
    localDate: '2026-09-15',
    timeZone: 'America/Detroit',
    timeZoneSource: 'user_profile',
    occurrenceDueDate: state === 'not_configured' || state === 'upcoming' ? null : '2026-09-15',
    nextDueDate:
      state === 'satisfied' || state === 'skipped_current_occurrence'
        ? '2026-09-29'
        : state === 'snoozed'
          ? '2026-09-18'
          : '2026-09-15',
    snoozedUntil: state === 'snoozed' ? '2026-09-18' : null,
    satisfiedByCheckInId: state === 'satisfied' ? 'check-in-complete' : null,
  });

export const populatedBodyCheckInFixture = bodyCheckInSchema.parse({
  contractVersion: BODY_CHECK_IN_CONTRACT_VERSION,
  id: 'check-in-complete',
  version: 2,
  date: '2026-09-15',
  localTime: '07:42',
  status: 'completed',
  mealContext: 'pre_meal',
  workoutContext: 'pre_workout',
  pumpPresent: false,
  unusualBloating: false,
  notes: 'Same tape, before breakfast.',
  protocolVersion: BODY_PROTOCOL_VERSION,
  source: 'agent_token',
  sourceId: 'agent-fixture',
  countAsScheduledOccurrence: true,
  measurements: [
    {
      id: 'measurement-waist',
      site: 'waist_iliac_crest_nhanes',
      laterality: 'none',
      unitAtEntry: 'cm',
      reading1Mm: 842,
      reading2Mm: 848,
      reading3Mm: null,
      canonicalMm: 845,
      quality: 'replicated',
      selectedReadingPair: [1, 2],
      protocolId: 'waist_iliac_crest_nhanes',
      protocolVersion: BODY_PROTOCOL_VERSION,
      protocolName: waistProtocol.name,
      protocolInstructions: waistProtocol.instructions,
      protocolSourceUrls: [...waistProtocol.sourceUrls],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'measurement-chest',
      site: 'chest_nipple_line_relaxed',
      laterality: 'none',
      unitAtEntry: 'cm',
      reading1Mm: 1010,
      reading2Mm: 1040,
      reading3Mm: 1015,
      canonicalMm: 1013,
      quality: 'high_variance',
      selectedReadingPair: [1, 3],
      protocolId: 'chest_nipple_line_relaxed',
      protocolVersion: BODY_PROTOCOL_VERSION,
      protocolName: chestProtocol.name,
      protocolInstructions: chestProtocol.instructions,
      protocolSourceUrls: [...chestProtocol.sourceUrls],
      createdAt: now + 1,
      updatedAt: now + 1,
    },
  ],
  completedAt: now - 500,
  correctedAt: now,
  correctedBySource: 'user',
  correctedBySourceId: null,
  correctionReason: 'Corrected chest transcription.',
  createdAt: now - 500,
  updatedAt: now,
});

const analyticsPoint = (
  date: string,
  suffix: string,
  site: 'waist_iliac_crest_nhanes' | 'chest_nipple_line_relaxed',
  canonicalMm: number,
) => ({
  checkInId: `analytics-check-in-${suffix}`,
  measurementId: `analytics-${site}-${suffix}`,
  date,
  checkInVersion: suffix === '3' ? 2 : 1,
  site,
  laterality: 'none' as const,
  canonicalMm,
  readingsMm: [canonicalMm - 2, canonicalMm + 2, null] as [number, number, null],
  unitAtEntry: 'cm' as const,
  quality: 'replicated' as const,
  protocolId: site,
  protocolVersion: BODY_PROTOCOL_VERSION,
  source: suffix === '2' ? ('agent_token' as const) : ('user' as const),
  sourceId: suffix === '2' ? 'agent-fixture' : null,
  corrected: suffix === '3',
  correctedAt: suffix === '3' ? now : null,
  correctionReason: suffix === '3' ? 'Corrected tape transcription.' : null,
  createdAt: now - (4 - Number(suffix)) * 86_400_000,
  updatedAt: now - (4 - Number(suffix)) * 86_400_000,
});

const waistPoints = [
  analyticsPoint('2026-08-15', '1', 'waist_iliac_crest_nhanes', 850),
  analyticsPoint('2026-08-29', '2', 'waist_iliac_crest_nhanes', 846),
  analyticsPoint('2026-09-15', '3', 'waist_iliac_crest_nhanes', 843),
];
const chestPoints = [
  analyticsPoint('2026-08-15', '1', 'chest_nipple_line_relaxed', 1010),
  analyticsPoint('2026-08-29', '2', 'chest_nipple_line_relaxed', 1012),
  analyticsPoint('2026-09-15', '3', 'chest_nipple_line_relaxed', 1015),
];

export const populatedBodyAnalyticsFixture = bodyProgressAnalyticsSchema.parse({
  range: {
    preset: '3m',
    startDate: '2026-06-15',
    endDate: '2026-09-15',
    asOfDate: '2026-09-15',
  },
  timeZone: 'America/Detroit',
  isHistorical: false,
  algorithm: {
    version: 'body-progress-analytics-v1',
    minimumCompatibleCheckIns: 3,
    minimumElapsedDays: 28,
    minimumSpacingDays: 10,
    freshnessGraceDays: 7,
    noiseFloorMm: {
      waist_iliac_crest_nhanes: 20,
      chest_nipple_line_relaxed: 10,
      hips_maximum: 10,
      upper_arm_midpoint_flexed: 10,
      thigh_midpoint: 10,
    },
    regression: 'dated_ordinary_least_squares',
    interpolation: 'none',
    highVariancePolicy: 'blocks_direction_preserves_history',
  },
  goal: {
    type: 'maintain',
    sourceContract: 'trend-weight-v1',
    goalId: 'goal-maintain',
    maintenanceBandState: 'inside_maintenance_band',
  },
  weight: {
    sourceContract: 'trend-weight-v1',
    sourceFingerprint: '1'.repeat(64),
    state: 'sufficient',
    direction: 'stable',
    trendWeight: 181.4,
    trendDate: '2026-09-15',
    recentPacePerWeek: -0.1,
    recentPaceEffectiveDate: '2026-09-15',
    paceFreshness: 'current',
    unit: 'lbs',
    observationCount: 12,
    spanDays: 28,
    latestAgeDays: 0,
  },
  readiness: {
    state: 'ready',
    completedCheckInCount: 3,
    compatibleSegmentCount: 2,
    supportedSegmentCount: 2,
    latestCompletedDate: '2026-09-15',
    cadenceDays: 14,
    enabledSites: [
      { site: 'waist_iliac_crest_nhanes', laterality: 'none' },
      { site: 'chest_nipple_line_relaxed', laterality: 'none' },
    ],
    reasonCodes: [],
  },
  segments: [
    {
      id: `waist_iliac_crest_nhanes:none:${BODY_PROTOCOL_VERSION}`,
      site: 'waist_iliac_crest_nhanes',
      laterality: 'none',
      protocolVersion: BODY_PROTOCOL_VERSION,
      noiseFloorMm: 20,
      points: waistPoints,
      rawDelta: {
        fromCheckInId: 'analytics-check-in-1',
        fromDate: '2026-08-15',
        fromCanonicalMm: 850,
        toCheckInId: 'analytics-check-in-3',
        toDate: '2026-09-15',
        toCanonicalMm: 843,
        deltaMm: -7,
      },
      analysis: {
        state: 'supported',
        direction: 'stable_within_measurement_noise',
        compatiblePointCount: 3,
        independentlySpacedPointCount: 3,
        elapsedDays: 31,
        latestAgeDays: 0,
        freshnessLimitDays: 21,
        slopeMmPerDay: -0.22,
        fittedTotalChangeMm: -6.8,
        reasonCodes: ['WAIST_STABLE'],
      },
      qualityStates: ['replicated'],
    },
    {
      id: `chest_nipple_line_relaxed:none:${BODY_PROTOCOL_VERSION}`,
      site: 'chest_nipple_line_relaxed',
      laterality: 'none',
      protocolVersion: BODY_PROTOCOL_VERSION,
      noiseFloorMm: 10,
      points: chestPoints,
      rawDelta: {
        fromCheckInId: 'analytics-check-in-1',
        fromDate: '2026-08-15',
        fromCanonicalMm: 1010,
        toCheckInId: 'analytics-check-in-3',
        toDate: '2026-09-15',
        toCanonicalMm: 1015,
        deltaMm: 5,
      },
      analysis: {
        state: 'supported',
        direction: 'stable_within_measurement_noise',
        compatiblePointCount: 3,
        independentlySpacedPointCount: 3,
        elapsedDays: 31,
        latestAgeDays: 0,
        freshnessLimitDays: 21,
        slopeMmPerDay: 0.16,
        fittedTotalChangeMm: 5,
        reasonCodes: ['CIRCUMFERENCES_STABLE'],
      },
      qualityStates: ['replicated'],
    },
  ],
  legacyPoints: [
    {
      entryId: 'legacy-1',
      date: '2026-07-01',
      site: 'waist',
      canonicalMm: 860,
      unitAtEntry: 'cm',
      provenance: 'legacy_unknown',
      compatibility: 'unsupported',
      limitation:
        'Legacy scalar record: no repeated-reading, exact protocol-version, or correction-history provenance.',
      createdAt: now - 1_000_000,
      updatedAt: now - 1_000_000,
    },
  ],
  strengthEvidence: {
    state: 'unavailable',
    confidence: 'unavailable',
    sourceContract: 'workout-progression-v1',
    sourceDates: [],
    recommendationIds: [],
    sourceFingerprints: [],
    reason: 'No current server-owned workout progression decisions were available in this range.',
  },
  signal: {
    state: 'maintenance_signal',
    confidence: 'medium',
    reasonCodes: [
      'WEIGHT_STABLE',
      'WAIST_STABLE',
      'CIRCUMFERENCES_STABLE',
      'STRENGTH_EVIDENCE_UNAVAILABLE',
      'INSIDE_MAINTENANCE_CORRIDOR',
    ],
    supportingFacts: [
      {
        code: 'WEIGHT_STABLE',
        label: 'Product Trend Weight is stable.',
        source: 'trend_weight',
        date: '2026-09-15',
      },
      {
        code: 'WAIST_STABLE',
        label: 'Waist is stable within the measurement noise floor.',
        source: 'body_check_ins',
        date: '2026-09-15',
      },
    ],
    contradictoryFacts: [],
    unavailableInputs: ['strength'],
    headline: 'Weight and compatible circumferences are stable within current evidence.',
    detail:
      'This supports a maintenance interpretation, while missing progression evidence limits confidence.',
    limitations: [
      'Circumference and weight trends do not measure body-fat percentage, fat mass, lean mass, or muscle gain.',
      'Noise floors are measurement policy, not medical or diagnostic thresholds.',
    ],
    nextAction: 'Continue the configured check-in cadence and compare the next compatible reading.',
  },
  markers: [
    {
      id: 'check-in:1',
      date: '2026-08-15',
      kind: 'check_in',
      label: 'Body check-in',
      sourceId: 'analytics-check-in-1',
    },
    {
      id: 'check-in:2',
      date: '2026-08-29',
      kind: 'check_in',
      label: 'Body check-in',
      sourceId: 'analytics-check-in-2',
    },
    {
      id: 'check-in:3',
      date: '2026-09-15',
      kind: 'check_in',
      label: 'Body check-in',
      sourceId: 'analytics-check-in-3',
    },
    {
      id: 'correction:3',
      date: '2026-09-15',
      kind: 'correction',
      label: 'Corrected body check-in',
      sourceId: 'analytics-check-in-3',
    },
  ],
  sourceFingerprint: '2'.repeat(64),
});
